# Generated by Django 5.1.4 on 2025-01-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedays',
            name='purpose',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Maternity/Paternity', 'Maternity/Paternity'), ('Others', 'Others'), ('Sick', 'Sick')], default='Annual', max_length=20),
        ),
    ]
