# Generated by Django 5.1.4 on 2025-01-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_leavedays_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
