# Generated by Django 5.1.4 on 2025-01-12 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.CharField(choices=[('Annual', 'Annual'), ('Maternity/Paternity', 'Maternity/Paternity'), ('Others', 'Others'), ('Sick', 'Sick')], default='Annual', max_length=20)),
                ('days_requested', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
