# Generated by Django 5.1.4 on 2025-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='timezone',
            field=models.CharField(default='GMT+3', max_length=10),
        ),
    ]
