# Generated by Django 5.1.4 on 2025-01-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_leaverequest_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='timezone',
        ),
    ]
