# Generated by Django 5.1.4 on 2025-02-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0009_alter_leavedays_user_timelog'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
