# Generated by Django 5.1.4 on 2025-02-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0010_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Human Resource Manager", "Human Resource Manager"),
                    ("General Manager", "General Manager"),
                    (
                        "Assistant Quality Assurance Manager",
                        "Assistant Quality Assurance Manager",
                    ),
                    ("Procurement Manager", "Procurement Manager"),
                    (
                        "Quality and Compliance Manager",
                        "Quality and Compliance Manager",
                    ),
                    ("Logistician", "Logistician"),
                    ("Accountant", "Accountant"),
                    ("Production Supervisor", "Production Supervisor"),
                    ("Inventory Supervisor", "Inventory Supervisor"),
                    ("Production Supervisor", "Production Supervisor"),
                    ("Production Manager", "Production Manager"),
                    ("Production Support", "Production Support"),
                    ("Janitor", "Janitor"),
                    ("Security Guard", "Security Guard"),
                    ("Managing Director", "Managing Director"),
                    ("Director", "Director"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
